name: Build Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  test:
    name: build project
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4  # 更新 checkout 版本

    - name: build_windows
      run: |
        $ENV:RUSTFLAGS='-C target-feature=+crt-static'
        rustup target add i686-pc-windows-msvc
        rustup target add x86_64-pc-windows-msvc
        cargo build --release --target i686-pc-windows-msvc
        cargo build --release --target x86_64-pc-windows-msvc
      shell: pwsh
        
    - name: before_windows_upload
      run: |
        mkdir Release
        cp target/i686-pc-windows-msvc/release/a2silk-cli.exe Release/a2silk-cli_windows_i686.exe
        cp target/x86_64-pc-windows-msvc/release/a2silk-cli.exe Release/a2silk-cli_windows_x86_64.exe
      shell: pwsh

    - name: upload file1
      uses: actions/upload-artifact@v4  # 更新 upload-artifact 版本
      with:
        name: a2silk-cli_windows_i686.exe
        path: Release/a2silk-cli_windows_i686.exe

    - name: upload file2
      uses: actions/upload-artifact@v4  # 更新 upload-artifact 版本
      with:
        name: a2silk-cli_windows_x86_64.exe
        path: Release/a2silk-cli_windows_x86_64.exe
